In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("dfTransjakarta180kRows.csv")

df.head(10)

,transID,payCardID,payCardBank,payCardName,payCardSex,payCardBirthDate,corridorID,corridorName,direction,tapInStops,...,tapInStopsLon,stopStartSeq,tapInTime,tapOutStops,tapOutStopsName,tapOutStopsLat,tapOutStopsLon,stopEndSeq,tapOutTime,payAmount
0,VRPJ892P3M98RA,3561407960318444,dki,"Dr. Janet Nashiruddin, M.Ak",M,2010,4,Pulo Gadung 2 - Tosari,1.0,P00167,...,106.89165,12,2023-04-03 06:53:02,P00127,Layur,-6.193539,106.89909,13.0,2023-04-03 07:13:28,3500.0
1,ZWCH834I6M26HS,347728053419394,emoney,Balamantri Rahayu,M,2002,JAK.28,Kp. Rambutan - Taman Wiladatika,1.0,B04633P,...,106.86298,27,2023-04-03 05:59:19,B00865P,Jln. Ar Ridho,-6.308148,106.86935,30.0,2023-04-03 06:57:06,0.0
2,YRLD835V6L82GO,377105453850671,emoney,Dian Mustofa,F,1993,B13,Bekasi Barat - Blok M,1.0,B02192P,...,106.99215,6,2023-04-03 05:13:24,B00108P,Bandar Djakarta Bekasi,-6.227085,106.99683,9.0,2023-04-03 06:01:23,20000.0
3,ZZBX143N6N83HQ,4486493302356581,dki,"Cut Janet Suryatmi, M.Ak",M,1980,8K,Batusari - Grogol,1.0,B03637P,...,106.78213,16,2023-04-03 05:20:24,NaN,Yayasan Alkahfi Jakbar,-6.198896,106.76889,26.0,2023-04-03 06:01:25,3500.0
4,EWEG491A2W45DR,30139379978125,bni,"dr. Mulyanto Pudjiastuti, M.Ak",F,1997,NaN,NaN,0.0,NaN,...,106.83514,2,2023-04-03 06:00:54,B02755P,Perpustakaan Nasional,-6.180673,106.82643,5.0,2023-04-03 06:47:32,3500.0
5,KTGG277R2I90ZB,30394281967910,bni,"Dasa Prakasa, S.I.Kom",F,1993,JAK.117,Tanjung Priok - Tanah Merdeka,1.0,B04272P,...,106.89638,17,2023-04-03 05:06:00,B04818P,Simpang Gotong Royong 2,-6.125482,106.89331,21.0,2023-04-03 05:41:04,0.0
6,VSJU956Z4T24LI,4974829151599657,dki,Elvina Hasanah,M,1966,9F,Rusun Tambora - Pluit,0.0,P00090,...,106.79352,5,2023-04-03 06:21:07,P00170,Penjaringan,-6.126306,106.79203,7.0,2023-04-03 06:52:58,0.0
7,HBMD368H3K77KW,3532177104809428,dki,"Perkasa Prakasa, M.Pd",F,2011,JAK.31,Blok M - Andara,0.0,B00042P,...,106.80369,55,2023-04-03 06:34:03,B01147P,Jln. H. Terin Pangkalan Jati,-6.327961,106.80054,56.0,2023-04-03 07:32:53,0.0
8,SQHG432Q6Z10BR,3537522260639116,dki,Ayu Wahyudin,F,2009,JAK.37,Cililitan - Condet via Kayu Manis,1.0,B05218P,...,106.85862,10,2023-04-03 05:48:17,B00405P,Gg. Ani Raya Condet,-6.266674,106.86054,37.0,2023-04-03 06:13:38,0.0
9,EHWL093H6L20UL,4677151756111287186,brizzi,"H. Xanana Santoso, S.Farm",M,2010,JAK.15,Bulak Turi - Tanjung Priok,0.0,B01327P,...,106.89550,46,2023-04-03 05:09:13,B05728P,Term. Tj. Priok 1,-6.109800,106.88118,52.0,2023-04-03 06:07:24,0.0

In [3]:
# Hitung titik tengah
mid = len(df) // 2

In [4]:
# Bagi jadi dua
df_part1 = df.iloc[:mid]
df_part2 = df.iloc[mid:]

# Simpan ke file baru
df_part1.to_csv("data_transjakarta_1.csv", index=False)
df_part2.to_csv("data_transjakarta_2.csv", index=False)

print("File berhasil dibagi jadi 2")

File berhasil dibagi jadi 2

In [5]:
df1 = pd.read_csv("data_transjakarta_1.csv")
df1

,transID,payCardID,payCardBank,payCardName,payCardSex,payCardBirthDate,corridorID,corridorName,direction,tapInStops,...,tapInStopsLon,stopStartSeq,tapInTime,tapOutStops,tapOutStopsName,tapOutStopsLat,tapOutStopsLon,stopEndSeq,tapOutTime,payAmount
0,VRPJ892P3M98RA,3561407960318444,dki,"Dr. Janet Nashiruddin, M.Ak",M,2010,4,Pulo Gadung 2 - Tosari,1.0,P00167,...,106.89165,12,2023-04-03 06:53:02,P00127,Layur,-6.193539,106.899090,13.0,2023-04-03 07:13:28,3500.0
1,ZWCH834I6M26HS,347728053419394,emoney,Balamantri Rahayu,M,2002,JAK.28,Kp. Rambutan - Taman Wiladatika,1.0,B04633P,...,106.86298,27,2023-04-03 05:59:19,B00865P,Jln. Ar Ridho,-6.308148,106.869350,30.0,2023-04-03 06:57:06,0.0
2,YRLD835V6L82GO,377105453850671,emoney,Dian Mustofa,F,1993,B13,Bekasi Barat - Blok M,1.0,B02192P,...,106.99215,6,2023-04-03 05:13:24,B00108P,Bandar Djakarta Bekasi,-6.227085,106.996830,9.0,2023-04-03 06:01:23,20000.0
3,ZZBX143N6N83HQ,4486493302356581,dki,"Cut Janet Suryatmi, M.Ak",M,1980,8K,Batusari - Grogol,1.0,B03637P,...,106.78213,16,2023-04-03 05:20:24,NaN,Yayasan Alkahfi Jakbar,-6.198896,106.768890,26.0,2023-04-03 06:01:25,3500.0
4,EWEG491A2W45DR,30139379978125,bni,"dr. Mulyanto Pudjiastuti, M.Ak",F,1997,NaN,NaN,0.0,NaN,...,106.83514,2,2023-04-03 06:00:54,B02755P,Perpustakaan Nasional,-6.180673,106.826430,5.0,2023-04-03 06:47:32,3500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94745,AYUG731J7I15WP,4060675934254982980,brizzi,Drs. Hani Utama,M,1983,1C,Pesanggrahan - Blok M,0.0,P00045,...,106.79783,34,2023-04-11 21:13:01,B06577P,Blok M Jalur 2,-6.243369,106.801880,35.0,2023-04-11 22:53:40,3500.0
94746,HHNG563Z3T52MJ,180068294800346,emoney,Fathonah Wahyuni,F,1986,12B,Pluit - Senen,0.0,B02886P,...,106.79090,0,2023-04-11 19:24:14,B05324P,SMKN 56,-6.119094,106.794230,1.0,2023-04-11 20:45:37,3500.0
94747,UNAW036H5S18ZV,4794628463414177,dki,Dasa Sitorus,F,2009,3A,Rusun Pesakih - Kalideres,0.0,B03286P,...,106.71698,0,2023-04-11 18:08:28,B02379P,Masjid Raya KH Hasyim Asyari,-6.159272,106.717080,1.0,2023-04-11 19:13:55,0.0
94748,DTJC918C2H41UF,503821322016,flazz,Nalar Damanik,M,1992,JAK.12,Tanah Abang - Kebayoran Lama via Pos Pengumben,0.0,B05221P,...,106.77024,41,2023-04-11 19:21:21,B04896P,Simpang Kampung Baru Assirat,-6.225618,106.771940,49.0,2023-04-11 20:22:27,0.0
94749,ESSK971T3J36AQ,213100007061782,emoney,Safina Nainggolan,F,2002,JIS3,Harmoni - Jakarta International Stadium,0.0,P00046,...,106.85805,8,2023-04-11 21:30:53,P00291,Harmoni Arah Utara,-6.162678,106.819663,13.0,2023-04-11 23:12:54,3500.0

In [6]:
df2 = pd.read_csv("data_transjakarta_2.csv")
df2

,transID,payCardID,payCardBank,payCardName,payCardSex,payCardBirthDate,corridorID,corridorName,direction,tapInStops,...,tapInStopsLon,stopStartSeq,tapInTime,tapOutStops,tapOutStopsName,tapOutStopsLat,tapOutStopsLon,stopEndSeq,tapOutTime,payAmount
0,ZJYB898V9R98ED,4897528453581548947,brizzi,Banawa Mandala,F,1990,8,Lebak Bulus - Pasar Baru via Tomang,1.0,P00176,...,106.816980,3,2023-04-11 20:10:01,P00187,Pos Pengumben,-6.212935,106.772260,14.0,2023-04-11 21:16:37,3500.0
1,DLBW159R6E00GH,4701047998022938,dki,"R.A. Laras Pangestu, S.IP",F,2006,M1H,Tanah Abang - St. Gondangdia,1.0,B05666P,...,106.814090,3,2023-04-11 21:13:59,B05445P,St. Gondangdia 2,-6.185054,106.832300,11.0,2023-04-11 22:56:10,NaN
2,WIDX220R5X91AV,3555473824753729,dki,"Rahman Palastri, S.Pd",M,1977,D21,Universitas Indonesia - Lebak Bulus,1.0,B00132P,...,106.786360,5,2023-04-11 19:39:48,B01405P,Jln. Muara 1,-6.304063,106.850610,19.0,2023-04-11 20:56:09,3500.0
3,IQAQ948D4T09YX,342036975037954,emoney,Lantar Jailani,M,1992,JAK.77,Tanjung Priok - Jembatan Item,0.0,B01954P,...,106.881300,46,2023-04-11 17:36:39,B03179P,RS Sukmul Sisma Medika,-6.112315,106.882360,47.0,2023-04-11 18:31:29,0.0
4,GDCW629Y9I61QQ,3594586987402215,dki,Yulia Yuliarti,M,2005,11C,Rusun Pinus Elok - Rusun Pulo Gebang,1.0,B00081P,...,106.938030,8,2023-04-11 19:24:21,B02800P,Perum Tpi 1,-6.197379,106.935130,14.0,2023-04-11 20:30:46,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94745,AEQP180C2Q77IS,378254320267609,emoney,"R.A. Malika Samosir, S.Kom",M,1998,JAK.43B,Tongtek - Tebet Eco Park (TEP) - Cililitan,1.0,B06271P,...,106.852860,24,2023-04-02 13:00:49,B03318P,Sawo Kecik Raya,-6.224852,106.854890,34.0,2023-04-02 14:54:30,0.0
94746,PJOF006Z8Q63II,5406087682675422,dki,Amalia Gunarto,M,1981,9C,Pinang Ranti - Bundaran Senayan,1.0,P00040,...,106.858140,9,2023-04-04 17:31:55,P00030,Cawang Ciliwung Arah Timur,-6.243012,106.863540,10.0,2023-04-04 18:38:31,3500.0
94747,NTSG621H8U49WW,4674674527076302608,brizzi,R.A. Lintang Wibisono,F,1998,6T,Pasar Minggu - Velbak,1.0,B06746P,...,106.808665,17,2023-04-05 10:37:19,B06750P,Sbr. SDN Cilandak Barat 15,-6.288628,106.806811,19.0,2023-04-05 12:20:28,3500.0
94748,PUNA543S2M10LX,4952762933693,online,Yunita Sitompul,F,1984,2,Pulo Gadung - Monas,1.0,P00005,...,106.888800,12,2023-04-14 13:34:20,P00192,Pulo Gadung 1,-6.183239,106.909070,15.0,2023-04-14 16:05:12,3500.0
94749,NRUZ377L2D82PG,2235668090485688,dki,Omar Rahayu,M,1997,8C,Kebayoran Lama - Tanah Abang,1.0,B02196P,...,106.814530,12,2023-04-29 09:14:32,B05223P,Simprug 1,-6.223678,106.790200,28.0,2023-04-29 11:53:39,3500.0

In [8]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,189490,189491,189492,189493,189494,189495,189496,189497,189498,189499
transID,VRPJ892P3M98RA,ZWCH834I6M26HS,YRLD835V6L82GO,ZZBX143N6N83HQ,EWEG491A2W45DR,KTGG277R2I90ZB,VSJU956Z4T24LI,HBMD368H3K77KW,SQHG432Q6Z10BR,EHWL093H6L20UL,...,WVYM898J9W51CV,ERLW484O0H06UL,QHPC294S1R67BW,DYOB765N0X83DF,GUCG964H1W85UJ,AEQP180C2Q77IS,PJOF006Z8Q63II,NTSG621H8U49WW,PUNA543S2M10LX,NRUZ377L2D82PG
payCardID,3561407960318444,347728053419394,377105453850671,4486493302356581,30139379978125,30394281967910,4974829151599657,3532177104809428,3537522260639116,4677151756111287186,...,3560745863909418,630402756526,3527844683580632,4477892629147428,213108168021420,378254320267609,5406087682675422,4674674527076302608,4952762933693,2235668090485688
payCardBank,dki,emoney,emoney,dki,bni,bni,dki,dki,dki,brizzi,...,dki,flazz,dki,dki,emoney,emoney,dki,brizzi,online,dki
payCardName,"Dr. Janet Nashiruddin, M.Ak",Balamantri Rahayu,Dian Mustofa,"Cut Janet Suryatmi, M.Ak","dr. Mulyanto Pudjiastuti, M.Ak","Dasa Prakasa, S.I.Kom",Elvina Hasanah,"Perkasa Prakasa, M.Pd",Ayu Wahyudin,"H. Xanana Santoso, S.Farm",...,Dt. Warta Yuliarti,"drg. Daniswara Winarno, S.Sos",Karsana Gunawan,Alambana Saputra,"Vanesa Aryani, M.M.","R.A. Malika Samosir, S.Kom",Amalia Gunarto,R.A. Lintang Wibisono,Yunita Sitompul,Omar Rahayu
payCardSex,M,M,F,M,F,F,M,F,F,M,...,M,M,F,M,M,M,M,F,F,M
payCardBirthDate,2010,2002,1993,1980,1997,1993,1966,2011,2009,2010,...,1989,2005,1989,2007,1971,1998,1981,1998,1984,1997
corridorID,4,JAK.28,B13,8K,NaN,JAK.117,9F,JAK.31,JAK.37,JAK.15,...,7E,8A,D21,12P,JAK.47,JAK.43B,9C,6T,2,8C
corridorName,Pulo Gadung 2 - Tosari,Kp. Rambutan - Taman Wiladatika,Bekasi Barat - Blok M,Batusari - Grogol,NaN,Tanjung Priok - Tanah Merdeka,Rusun Tambora - Pluit,Blok M - Andara,Cililitan - Condet via Kayu Manis,Bulak Turi - Tanjung Priok,...,Kampung Rambutan - Ragunan,Jelambar - Juanda,Universitas Indonesia - Lebak Bulus,St. LRT Pegangsaan Dua - JIS,Pasar Minggu - Ciganjur via KB Ragunan,Tongtek - Tebet Eco Park (TEP) - Cililitan,Pinang Ranti - Bundaran Senayan,Pasar Minggu - Velbak,Pulo Gadung - Monas,Kebayoran Lama - Tanah Abang
direction,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0
tapInStops,P00167,B04633P,B02192P,B03637P,NaN,B04272P,P00090,B00042P,B05218P,B01327P,...,B05697P,P00176,B00402P,B00166P,B04002P,B06271P,P00040,B06746P,P00005,B02196P
tapInStopsName,Pemuda Rawamangun,Sekolah Islam PB Soedirman,Mall Metropolitan,Sbr. Jln. Angsana Kemanggisan,BRI Menteng,Sbr. RPTRA Radar Pembangunan,Jembatan Dua,Andara Margasatwa 1,Simpang Waru Tengah,Jln. Lorong 5,...,Telkomsel Jln. Nangka,Petojo,Gg. Ampera BMW Astra,Boulevard Bukit Gading Raya,Sbr. Madrasah Aliyah Citra Cendekia,Simpang Tebet Raya Timur 1,Cikoko Stasiun Cawang Arah Timur,Sbr. Jln. Pangeran Antasari,ASMI,Mall Thamrin City
tapInStopsLat,-6.193488,-6.314293,-6.247861,-6.194813,-6.186792,-6.120126,-6.143279,-6.313471,-6.293301,-6.107716,...,-6.304254,-6.169984,-6.292546,-6.15515,-6.357553,-6.229718,-6.243028,-6.275209,-6.171797,-6.194341
tapInStopsLon,106.89165,106.86298,106.99215,106.78213,106.83514,106.89638,106.79352,106.80369,106.85862,106.8955,...,106.84593,106.81698,106.790025,106.89579,106.80076,106.85286,106.85814,106.808665,106.8888,106.81453
stopStartSeq,12,27,6,16,2,17,5,55,10,46,...,13,2,23,5,47,24,9,17,12,12
tapInTime,2023-04-03 06:53:02,2023-04-03 05:59:19,2023-04-03 05:13:24,2023-04-03 05:20:24,2023-04-03 06:00:54,2023-04-03 05:06:00,2023-04-03 06:21:07,2023-04-03 06:34:03,2023-04-03 05:48:17,2023-04-03 05:09:13,...,2023-04-20 12:27:15,2023-04-04 05:33:13,2023-04-18 19:04:10,2023-04-03 20:38:52,2023-04-25 15:53:45,2023-04-02 13:00:49,2023-04-04 17:31:55,2023-04-05 10:37:19,2023-04-14 13:34:20,2023-04-29 09:14:32
tapOutStops,P00127,B00865P,B00108P,NaN,B02755P,B04818P,P00170,B01147P,B00405P,B05728P,...,P00199,P00209,B02895P,NaN,B05670P,B03318P,P00030,B06750P,P00192,B05223P
tapOutStopsName,Layur,Jln. Ar Ridho,Bandar Djakarta Bekasi,Yayasan Alkahfi Jakbar,Perpustakaan Nasional,Simpang Gotong Royong 2,Penjaringan,Jln. H. Terin Pangkalan Jati,Gg. Ani Raya Condet,Term. Tj. Priok 1,...,Ragunan,RS Tarakan,Poins Square,Jln. Sunter Permai 2,Tanah Baru Cipedak,Sawo Kecik Raya,Cawang Ciliwung Arah Timur,Sbr. SDN Cilandak Barat 15,Pulo Gadung 1,Simprug 1
tapOutStopsLat,-6.193539,-6.308148,-6.227085,-6.198896,-6.180673,-6.125482,-6.126306,-6.327961,-6.266674,-6.1098,...,-6.305769,-6.171146,-6.289207,-6.131551,-6.363462,-6.224852,-6.243012,-6.288628,-6.183239,-6.223678
tapOutStopsLon,106.89909,106.86935,106.99683,106.76889,106.82643,106.89331,106.79203,106.80054,106.86054,106.88118,...,106.81949,106.81011,106.77718,106.86248,106.80684,106.85489,106.86354,106.806811,106.90907,106.7902
stopEndSeq,13.0,30.0,9.0,26.0,5.0,21.0,7.0,56.0,37.0,52.0,...,21.0,3.0,26.0,14.0,50.0,34.0,10.0,19.0,15.0,28.0
tapOutTime,2023-04-03 07:13:28,2023-04-03 06:57:06,2023-04-03 06:01:23,2023-04-03 06:01:25,2023-04-03 06:47:32,2023-04-03 05:41:04,2023-04-03 06:52:58,2023-04-03 07:32:53,2023-04-03 06:13:38,2023-04-03 06:07:24,...,2023-04-20 15:26:20,2023-04-04 05:53:25,2023-04-18 21:41:17,2023-04-03 21:48:16,2023-04-25 16:27:31,2023-04-02 14:54:30,2023-04-04 18:38:31,2023-04-05 12:20:28,2023-04-14 16:05:12,2023-04-29 11:53:39
payAmount,3500.0,0.0,20000.0,3500.0,3500.0,0.0,0.0,0.0,0.0,0.0,...,3500.0,3500.0,3500.0,3500.0,0.0,0.0,3500.0,3500.0,3500.0,3500.0

In [7]:
df.dtypes

transID              object
payCardID             int64
payCardBank          object
payCardName          object
payCardSex           object
payCardBirthDate      int64
corridorID           object
corridorName         object
direction           float64
tapInStops           object
tapInStopsName       object
tapInStopsLat       float64
tapInStopsLon       float64
stopStartSeq          int64
tapInTime            object
tapOutStops          object
tapOutStopsName      object
tapOutStopsLat      float64
tapOutStopsLon      float64
stopEndSeq          float64
tapOutTime           object
payAmount           float64
dtype: object

In [11]:
df.duplicated().sum()

0

In [ ]:
def load_data():

    data = pd.read_csv(CSV_PATH)

In [9]:
df.isna().sum()

transID                 0
payCardID               0
payCardBank             0
payCardName             0
payCardSex              0
payCardBirthDate        0
corridorID           6980
corridorName        13528
direction               0
tapInStops           7241
tapInStopsName          0
tapInStopsLat           0
tapInStopsLon           0
stopStartSeq            0
tapInTime               0
tapOutStops         12369
tapOutStopsName      6720
tapOutStopsLat       6720
tapOutStopsLon       6720
stopEndSeq           6720
tapOutTime           6720
payAmount            3718
dtype: int64

In [ ]:
from airflow import DAG
from airflow.operators.python import PythonOperator
from datetime import datetime
import pandas as pd
# import requests
from sqlalchemy import create_engine, text


# ================== CONFIG ==================
DB_USER = "postgres"
DB_PASSWORD = "admin"
DB_HOST = "host.docker.internal"
DB_PORT = "5432"
DB_NAME = "etl_test"
SOURCE_CSV_PATH = "/opt/airflow/data/data_transjakarta_1.csv"
TABLE_NAME = "transjakarta_trx"


def extract_data_tj():

    df = pd.read_csv(SOURCE_CSV_PATH)
    df.to_csv("/opt/airflow/data/raw_tj.csv", index=False)
    print("Extract selesai")

def transform_data_tj():
    df = pd.read_csv("/opt/airflow/data/raw_tj.csv")

    #drop null values
    df = df.dropna()

    #convert date
    df['tapInTime'] = pd.to_datetime(df['tapInTime'])
    df['tapOutTime'] = pd.to_datetime(df['tapOutTime'])

    #save to clean csv
    df.to_csv("/opt/airflow/data/clean_tj.csv", index=False)


def load_data_tj():
    df = pd.read_csv("/opt/airflow/data/clean_tj.csv")

    engine = create_engine(
        f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
    )

    #append to table
    df.to_sql(TABLE_NAME, engine, if_exists="append", index=False)


with DAG(
    dag_id="transjakarta_csv_etl",
    start_date=datetime(2026, 1, 1),
    schedule_interval=None,
    catchup=False,
    tags=["etl", "transfrom", "postgres"]
)as dag:

    extract_data_tj_task = PythonOperator(
        task_id="extract_data_tj",
        python_callable=extract_data_tj
    )

    transform_data_tj_task = PythonOperator(
        task_id="transform_data_tj",
        python_callable=transform_data_tj
    )

    load_data_tj_task = PythonOperator(
        task_id="load_data_tj",
        python_callable=load_data_tj
    )
    
    extract_data_tj_task >> transform_data_tj_task >> load_data_tj_task